//POST ACTIONS
export const ADD_POST = 'ADD_POST';
export const CREATED_POST = 'CREATED_POST';
export const EDITED_POST = 'EDITED_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const REMOVED_POST = 'REMOVED_POST';
export const RECEIVE_POST = "RECEIVE_POST";
export const REQUEST_POSTS = "REQUEST_POSTS";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const FILTER_POSTS = 'FILTER_POSTS';
export const REQUEST_VOTE = 'REQUEST_VOTE';
export const RECEIVED_VOTE = 'RECEIVED_VOTE';

//COMMENT ACTIONS
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const REMOVED_COMMENT = 'REMOVED_COMMENT';
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const REQUEST_COMMENT_OPERATION = 'REQUEST_COMMENT_OPERATION';

//CATEGORIES ACTIONS
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";

//UTIL ACTIONS
export const TOOGLE = 'TOOGLE';
export const CHANGE_SORT = 'CHANGE_SORT';






